import type { Metadata } from "next";
import { Roboto_Mono as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import Image from "next/image";
import Footer from "@/components/Main/Footer/Footer";

import { Toaster } from "@/components/ui/toaster";

const fontSans = FontSans({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Faran.dev",
  description: "Generated by create next app",
  icons: {
    icon: "/cock.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <div className="w-screen h-screen flex flex-col">
          <nav className="flex p-10 w-screen h-20">
            <div className="w-full h-full flex justify-between items-center">
              <div className="flex gap-5 justify-center items-center">
                <div>
                  <Image src={"/logo.svg"} alt="logo" width={30} height={30} />
                </div>
                <div>
                  Faran.<span className="text-green-800">dev</span>
                </div>
              </div>
              <div className="flex gap-6">
                <Link href={"/"} className="hover:text-green-800">
                  Home
                </Link>
                <Link href={"#Expereince"} className="hover:text-green-800">
                  Experience
                </Link>
                <Link href={"#projects"} className="hover:text-green-800">
                  Projects
                </Link>
                <Link href={"#Reviews"} className="hover:text-green-800">
                  Recommendations
                </Link>
              </div>
              <div>
                <Link
                  href={"/Resume"}
                  className=""
                >
                  <Button className="bg-white border-2 border-green-800 text-green-800 hover:bg-green-800 hover:text-white">
                    Resume
                  </Button>
                </Link>
              </div>
            </div>
          </nav>
          {children}
          <Toaster />
          <div className="flex h-full w-full justify-end items-end mt-10">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
